// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhTRrPchD5JCQpg7y6sFPzLD4_SHJiXK8',
    appId: '1:696400102473:web:63605a99acb0d8f54c2b98',
    messagingSenderId: '696400102473',
    projectId: 'lab-assignment-8-603cf',
    authDomain: 'lab-assignment-8-603cf.firebaseapp.com',
    storageBucket: 'lab-assignment-8-603cf.firebasestorage.app',
    measurementId: 'G-XDGHNWESDE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCG1fboxx1ZcOlYSxMrV0uTRUgTKRDy5f4',
    appId: '1:696400102473:android:f3bf02fc22a921da4c2b98',
    messagingSenderId: '696400102473',
    projectId: 'lab-assignment-8-603cf',
    storageBucket: 'lab-assignment-8-603cf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5h5IYbHvDhddJCa6N5mjkyRdjkFwNQrk',
    appId: '1:696400102473:ios:8532c71f85a03d934c2b98',
    messagingSenderId: '696400102473',
    projectId: 'lab-assignment-8-603cf',
    storageBucket: 'lab-assignment-8-603cf.firebasestorage.app',
    iosBundleId: 'com.example.labAssignment8',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5h5IYbHvDhddJCa6N5mjkyRdjkFwNQrk',
    appId: '1:696400102473:ios:8532c71f85a03d934c2b98',
    messagingSenderId: '696400102473',
    projectId: 'lab-assignment-8-603cf',
    storageBucket: 'lab-assignment-8-603cf.firebasestorage.app',
    iosBundleId: 'com.example.labAssignment8',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhTRrPchD5JCQpg7y6sFPzLD4_SHJiXK8',
    appId: '1:696400102473:web:0a1d228d28773ae84c2b98',
    messagingSenderId: '696400102473',
    projectId: 'lab-assignment-8-603cf',
    authDomain: 'lab-assignment-8-603cf.firebaseapp.com',
    storageBucket: 'lab-assignment-8-603cf.firebasestorage.app',
    measurementId: 'G-2SPMQH934W',
  );
}
